apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-sygnal
  namespace: {{ .Values.namespace }}
data:
  sygnal.yaml: |-
    log:
      setup:
        version: 1
        formatters:
          normal:
            format: '%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s'
        handlers:
          stderr:
            class: 'logging.StreamHandler'
            formatter: 'normal'
            stream: 'ext://sys.stderr'
          stdout:
            class: 'logging.StreamHandler'
            formatter: 'normal'
            stream: 'ext://sys.stdout'
          file:
            class: 'logging.handlers.WatchedFileHandler'
            formatter: 'normal'
            filename: './sygnal.log'
        loggers:
          sygnal.access:
            propagate: false
            handlers: ['stdout']
            level: 'INFO'
          sygnal:
            propagate: false
            handlers: ['stderr', 'file']
        root:
          handlers: ['stderr']
          level: 'INFO'
        disable_existing_loggers: false
      access:
        x_forwarded_for: false
    http:
      bind_addresses: ['0.0.0.0']
      port: 5000
    apps:
      com.exampleapp.app.webpush:
        type: webpush
        vapid_private_key: '/configs/private_key.pem'
        vapid_contact_email: mailto:contact@exampleapp.com
        ttl: 900
        allowed_endpoints:
          - 'updates.push.services.mozilla.com'
          - 'fcm.googleapis.com'
          - '*.notify.windows.com'
          - '*.push.apple.com'
