apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-sygnal
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: sygnal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sygnal
    spec:
      containers:
        - image: matrixdotorg/sygnal:v0.12.0
          name: sygnal
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: sygnal-config
              mountPath: /configs/sygnal.yaml
              subPath: sygnal.yaml
              readOnly: true
            - name: private-key
              mountPath: /configs/private_key.pem
              subPath: {{ .Values.privateKeySecret.fileName }}
              readOnly: true
          env:
            - name: SYGNAL_CONF
              value: /configs/sygnal.yaml
          ports:
            - containerPort: 5000
      volumes:
        - name: sygnal-config
          configMap:
            name: matrix-sygnal
        - name: private-key
          secret:
            secretName: {{ .Values.privateKeySecret.secretName }}