{{- if and (eq .Values.service.type "NodePort") (not .Values.service.nodePort) }}
{{- fail "nodePort value must be specified when type is NodePort." }}
{{- end }}

apiVersion: v1
kind: Service
metadata:
  name: matrix-sygnal
  namespace: {{ .Values.namespace }}
  labels:
    app: sygnal
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if ne .Values.service.type "None" }}
  selector:
    app: sygnal
  {{- end }}